Update to Microsoft.CodeAnalysis 3.3.1 (#5163)
* Update to Microsoft.CodeAnalysis 3.3.1

This updates to the latest Microsoft.CodeAnalysis packages for C#8
support.

Fixes the following error on a project that uses nullable reference
types:

Microsoft.DocAsCode.Exceptions.DocfxException: Unable to generate spec reference for !: ---> System.IO.InvalidDataException: Fail to parse id for symbol  in namespace .
  at Microsoft.DocAsCode.Metadata.ManagedReference.YamlModelGenerator.AddSpecReference (Microsoft.CodeAnalysis.ISymbol symbol, System.Collections.Generic.IReadOnlyList`1[T] typeGenericParameters, System.Collections.Generic.IReadOnlyList`1[T] methodGenericParameters, System.Collections.Generic.Dictionary`2[TKey,TValue] references, Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter adapter) [0x0005e] in <27b606b838ab45b788854d5e45efa610>:0
  at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.AddSpecReference (Microsoft.CodeAnalysis.ISymbol symbol, System.Collections.Generic.IReadOnlyList`1[T] typeGenericParameters, System.Collections.Generic.IReadOnlyList`1[T] methodGenericParameters) [0x00000] in <27b606b838ab45b788854d5e45efa610>:0

* Fix TODO for space after tuple

Since updating Microsoft.CodeAnalysis to 3.3.1, the automatic formatting
for tuples in C# has been fixed, so update tests accordingly.

https://github.com/dotnet/roslyn/pull/29405

* Fix TestCSharpFeature_Default_7_1Class

Since updating to Microsoft.CodeAnalysis 3.3.1, the default keyword is
resolved to a vaule instead of the a default expression.

Probably comes from https://github.com/dotnet/roslyn/pull/37596